apiVersion: v1
kind: Pod
metadata:
  name: fortune3
spec:
  containers:
  - image: luksa/fortune:env
    env:
      - name: INTERVAL
        value: "30"
      - name: TUTU
        value: "tratata"
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
